name: Android CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RVX_SENTRY_DSN: ${{ vars.RVX_SENTRY_DSN }}
      RVX_ANALYSIS_ENABLED: ${{ vars.RVX_ANALYSIS_ENABLED }}
      RVX_ANALYSIS_BASEURL: ${{ vars.RVX_ANALYSIS_BASEURL }}
      RVX_DEBUG_APP_NAME: ${{ vars.RVX_DEBUG_APP_NAME }}
      RVX_BUILD_FLAVOUR_ID: ${{ vars.RVX_BUILD_FLAVOUR_ID }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle


      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --no-daemon assembleDebug

      - name: Archive debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          retention-days: 5
          path: |
            app/build/outputs/apk/debug/app-debug.apk
